FROM openjdk:8-jdk-alpine

ENV SCALA_VERSION=2.11.6
ENV SBT_VERSION=0.13.8
ENV SCALA_HOME=/usr/share/scala
ENV SBT_HOME /usr/local/sbt
ENV PATH ${PATH}:${SBT_HOME}/bin


RUN apk add --update-cache \
    bash \ 
  && rm -rf /var/cache/apk/*
  