# This Dockerfile has two required ARGs to determine which base image
# to use for the JDK and which sbt version to install.
FROM openjdk:8-jdk-alpine

ENV SCALA_VERSION=2.11.6
ENV SBT_VERSION=0.13.8
ENV SCALA_HOME=/usr/share/scala
ENV SBT_HOME /usr/local/sbt
ENV PATH ${PATH}:${SBT_HOME}/bin


RUN apk add --update-cache \
    curl \
    bash \ 
    procps \
    nodejs \
    npm \
    maven \
    gettext \
    python3 \
    py3-pip 
  # && pip install virtualenv \
  # && rm -rf /var/cache/apk/*



RUN apk add --update-cache ca-certificates && \
	curl -sL "http://dl.bintray.com/sbt/native-packages/sbt/$SBT_VERSION/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /usr/local && \
  echo -ne "- with sbt $SBT_VERSION\n" >> /root/.built


# RUN apk add --no-cache --virtual=.build-dependencies wget ca-certificates && \
#     apk add --no-cache bash curl jq && \
#     cd "/tmp" && \
#     wget --no-verbose "https://downloads.typesafe.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz" && \
#     tar xzf "scala-${SCALA_VERSION}.tgz" && \
#     mkdir "${SCALA_HOME}" && \
#     rm "/tmp/scala-${SCALA_VERSION}/bin/"*.bat && \
#     mv "/tmp/scala-${SCALA_VERSION}/bin" "/tmp/scala-${SCALA_VERSION}/lib" "${SCALA_HOME}" && \
#     ln -s "${SCALA_HOME}/bin/"* "/usr/bin/" && \
#     apk del .build-dependencies && \
#     rm -rf "/tmp/"*

# install newman
RUN npm -g install newman

# install awscli
RUN pip3 install awscli

RUN rm -rf /var/cache/apk/*